# File: monitoring/prometheus/rules/bookstore-alerts.yml
groups:
  - name: bookstore-application
    rules:
      - alert: ApplicationDown
        expr: up{job="bookstore-app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Bookstore application is down"
          description: "The bookstore application has been down for more than 1 minute."

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_server_requests_seconds_bucket{job="bookstore-app"}[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for more than 5 minutes."

      - alert: HighCPUUsage
        expr: process_cpu_usage{job="bookstore-app"} > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value | humanizePercentage }} for more than 5 minutes."

      - alert: HighMemoryUsage
        expr: (jvm_memory_used_bytes{job="bookstore-app", area="heap"} / jvm_memory_max_bytes{job="bookstore-app", area="heap"}) > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "JVM heap memory usage is {{ $value | humanizePercentage }} for more than 5 minutes."

      - alert: DatabaseConnectionErrors
        expr: increase(hikaricp_connections_creation_failed_total{job="bookstore-app"}[5m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database connection errors"
          description: "Database connection creation failed {{ $value }} times in the last 5 minutes."

  - name: system-monitoring
    rules:
      - alert: HighSystemCPU
        expr: 100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High system CPU usage"
          description: "System CPU usage is above 80% for more than 5 minutes."

      - alert: HighSystemMemory
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High system memory usage"
          description: "System memory usage is above 90% for more than 5 minutes."

      - alert: DiskSpaceLow
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Disk space low"
          description: "Disk space usage is above 90% on {{ $labels.device }} for more than 5 minutes."

  - name: container-monitoring
    rules:
      - alert: ContainerHighCPU
        expr: rate(container_cpu_usage_seconds_total{name=~"bookstore.*"}[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container high CPU usage"
          description: "Container {{ $labels.name }} CPU usage is {{ $value | humanizePercentage }} for more than 5 minutes."

      - alert: ContainerHighMemory
        expr: (container_memory_usage_bytes{name=~"bookstore.*"} / container_spec_memory_limit_bytes{name=~"bookstore.*"}) > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container high memory usage"
          description: "Container {{ $labels.name }} memory usage is {{ $value | humanizePercentage }} for more than 5 minutes."