name: Build, Test, and Deploy Bookstore App 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Maven
        run: mvn -f bookstore/pom.xml clean package

     - name: Build Docker image
       run: docker build -t bookstore-app -f bookstore/Dockerfile bookstore

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/bookstore/docker-compose.yml"

      - name: Copy built jar to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "bookstore/target/bookstore-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/bookstore/"

      - name: SSH and deploy Docker Compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/bookstore
            docker-compose down
            docker-compose up -d --build
